# Web Scraping COVID-19

In [10]:
# Importing the dependencies 
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

In [77]:
# Importing data from the websites
url = BeautifulSoup('https://www.worldometers.info/coronavirus/','html.parser')

soup = requests.get(url)
soup

C:\Users\MSI\AppData\Local\Temp\ipykernel_42900\1085019075.py:2: MarkupResemblesLocatorWarning: The input looks more like a URL than markup. You may want to use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  url = BeautifulSoup('https://www.worldometers.info/coronavirus/','html.parser')

In [78]:
#Converting into .lxml format
code = BeautifulSoup(soup.text, 'lxml') 
code = code.table                          #scrapping the live market table from website
code

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>129,998,931</td>
<td>+6,444</td>
<td>1,664,010</td>
<td>+13</td>
<td>125,527,099</td>
<td>+19,266</td>
<td>2,807,822</td>
<td>6,909</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>221,086,509</td>
<td>+1,238</td>
<td>1,552,249</td>
<td>+5</td>
<td>205,236,590</td>
<td>+8,726</td>
<td>14,297,670</td>
<td>14,731</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>252,419,058</td>
<td>+80,287</td>
<td>2,090,176</td>
<td>+186</td>
<td>247,735,285</td>
<td>+107,833</td>
<td>2,593,597</td>
<td>4,727</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>69,426,097</td>
<td></td>
<td>1,363,953</td>
<td></td>
<td>66,581,324</td>
<td></td>
<td>1,480,820</td>
<td>8,969</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>14,692,469</td>
<td></td>
<td>31,860</td>
<td></td>
<td>14,512,485</td>
<td></td>
<td>148,124</td>
<td>50</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,856,833</td>
<td></td>
<td>258,873</td>
<td></td>
<td>12,089,735</td>
<td></td>
<td>508,225</td>
<td>542</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>700,480,618</td>
<td>+87,969</td>
<td>6,961,136</td>
<td>+204</td>
<td>671,683,224</td>
<td>+135,825</td>
<td>21,836,258</td>
<td>35,928</td>
<td>89,865</td>
<td>893.0</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">110,047,807</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6,444</td>
<td style="font-weight: bold; text-align:right;">1,190,000                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+13</td>
<td style="font-weight: bold; text-align:right">107,820,312</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+15,017</td>
<td style="text-align:right;font-weight:bold;">1,037,495</td>
<td style="font-weight: bold; text-align:right">1,754</td>
<td style="font-weight: bold; text-align:right">328,692</td>
<td style="font-weight: bold; text-align:right">3,554</td>
<td style="font-weight: bold; text-align:right">1,186,546,440</td>
<td style="font-weight: bold; text-align:right">3,543,990</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>281</td><td>0</td>
<td style="font-weight: bold; text-align:right">19</td>
<td style="font-weight: bold; text-align:right">0.04</td>
<td style="font-weight: bold; text-align:right">3,099</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">45,009,660</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,040</td>
<td style="font-weight: bold; text-align:right;">533,337                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+4</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">31,998</td>
<td style="font-weight: bold; text-align:right">379</td>
<td style="font-weight: bold; text-align:right">930,797,975</td>
<td style="font-weight: bold; text-align:right">661,721</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,637</td><td>2</td>
<td style="font-weight: bold; text-align:right">0.7</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3</td>
</tr>
<tr style="background-color:#F0F0F0">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">40,138,560</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">167,642                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,970,918</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">612,013</td>
<td style="font-weight: bold; text-align:right">2,556</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>391</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">38,751,299</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">179,854                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">38,240,600</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">330,845</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">461,965</td>
<td style="font-weight: bold; text-align:right">2,144</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>466</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3,944</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">38,160,672</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">708,373                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">36,249,161</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,203,138</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">177,200</td>
<td style="font-weight: bold; text-align:right">3,289</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>304</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">5,587</td>
</tr>
<tr style="background-color:#F0F0F0">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">34,571,873</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">35,934                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">34,535,939</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">673,523</td>
<td style="font-weight: bold; text-align:right">700</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>1</td><td>1,428</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">33,803,572</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">74,694                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">269,169</td>
<td style="font-weight: bold; text-align:right">595</td>
<td style="font-weight: bold; text-align:right">100,414,883</td>
<td style="font-weight: bold; text-align:right">799,578</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>4</td><td>1,681</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">95,582</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">26,591,441</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">194,489                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">26,162,862</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">234,090</td>
<td style="font-weight: bold; text-align:right">240</td>
<td style="font-weight: bold; text-align:right">441,258</td>
<td style="font-weight: bold; text-align:right">3,227</td>
<td style="font-weight: bold; text-align:right">278,771,518</td>
<td style="font-weight: bold; text-align:right">4,625,933</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>310</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3,884</td>
</tr>
<tr style="background-color:#F0F0F0">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,812,582</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">232,112                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,580,470</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">0</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">362,239</td>
<td style="font-weight: bold; text-align:right">3,389</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>295</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">23,713,738</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+79,032</td>
<td style="font-weight: bold; text-align:right;">401,214                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+186</td>
<td style="font-weight: bold; text-align:right">23,068,286</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+98,252</td>
<td style="text-align:right;font-weight:bold;">244,238</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">162,639</td>
<td style="font-weight: bold; text-align:right">2,752</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>363</td><td>1</td>
<td style="font-weight: bold; text-align:right">542</td>

## Extracting the Table from Worldometers.com/coronavirus

In [79]:
covid_title = code.find('tr')
covid_title

<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>

In [35]:
covid_table_title = [title.text.strip() for title in covid_title]
print(covid_table_title)       # We are getting the tables as well as empty list

['', '#', '', 'Country,Other', '', 'TotalCases', '', 'NewCases', '', 'TotalDeaths', '', 'NewDeaths', '', 'TotalRecovered', '', 'NewRecovered', '', 'ActiveCases', '', 'Serious,Critical', '', 'Tot\xa0Cases/1M pop', '', 'Deaths/1M pop', '', 'TotalTests', '', 'Tests/\n1M pop', '', 'Population', '', 'Continent', '', '1 Caseevery X ppl', '1 Deathevery X ppl', '1 Testevery X ppl', '', 'New Cases/1M pop', '', 'New Deaths/1M pop', '', 'Active Cases/1M pop', '']

In [43]:
# So remove the empty table from the list we used following loop
new_covid_table_title = []
for i in covid_table_title:
    if i:
        new_covid_table_title.append(i)
    else:
        pass
new_covid_table_title

['#',
 'Country,Other',
 'TotalCases',
 'NewCases',
 'TotalDeaths',
 'NewDeaths',
 'TotalRecovered',
 'NewRecovered',
 'ActiveCases',
 'Serious,Critical',
 'Tot\xa0Cases/1M pop',
 'Deaths/1M pop',
 'TotalTests',
 'Tests/\n1M pop',
 'Population',
 'Continent',
 '1 Caseevery X ppl',
 '1 Deathevery X ppl',
 '1 Testevery X ppl',
 'New Cases/1M pop',
 'New Deaths/1M pop',
 'Active Cases/1M pop']

In [44]:
df = pd.DataFrame(columns = new_covid_table_title)
df

Empty DataFrame
Columns: [#, Country,Other, TotalCases, NewCases, TotalDeaths, NewDeaths, TotalRecovered, NewRecovered, ActiveCases, Serious,Critical, TotÂ Cases/1M pop, Deaths/1M pop, TotalTests, Tests/
1M pop, Population, Continent, 1 Caseevery X ppl, 1 Deathevery X ppl, 1 Testevery X ppl, New Cases/1M pop, New Deaths/1M pop, Active Cases/1M pop]
Index: []

[0 rows x 22 columns]

In [107]:
column_data = code.find_all('tr')
column_data[9]            # Checking where the value of USA is set as it is on the top of the list

<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">110,047,807</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6,444</td>
<td style="font-weight: bold; text-align:right;">1,190,000                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+13</td>
<td style="font-weight: bold; text-align:right">107,820,312</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+15,017</td>
<td style="text-align:right;font-weight:bold;">1,037,495</td>
<td style="font-weight: bold; text-align:right">1,754</td>
<td style="font-weight: bold; text-align:right">328,692</td>
<td style="font-weight: bold; text-align:right">3,554</td>
<td style="font-weight: bold; text-align:right">1,186,546,440</td>
<td style="font-weight: bold; text-align:right">3,543,990</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>281</td><td>0</td>
<td style="font-weight: bold; text-align:right">19</td>
<td style="font-weight: bold; text-align:right">0.04</td>
<td style="font-weight: bold; text-align:right">3,099</td>
</tr>

In [110]:
for row in column_data[9:]:        # Getting rid of the first eight cause it had other continents 
    row_data = row.find_all('td')
    individual_covid_data = [data.text.strip() for data in row_data]
    print(individual_covid_data)
    
    length = len(df)
    df.loc[length] = individual_covid_data

['1', 'USA', '110,047,807', '+6,444', '1,190,000', '+13', '107,820,312', '+15,017', '1,037,495', '1,754', '328,692', '3,554', '1,186,546,440', '3,543,990', '334,805,269', 'North America', '3', '281', '0', '19', '0.04', '3,099']
['2', 'India', '45,009,660', '+1,040', '533,337', '+4', 'N/A', 'N/A', 'N/A', 'N/A', '31,998', '379', '930,797,975', '661,721', '1,406,631,776', 'Asia', '31', '2,637', '2', '0.7', '', '3']
['3', 'France', '40,138,560', '', '167,642', '', '39,970,918', '', '0', '', '612,013', '2,556', '271,490,188', '4,139,547', '65,584,518', 'Europe', '2', '391', '0', '', '', '']
['4', 'Germany', '38,751,299', '', '179,854', '', '38,240,600', '', '330,845', 'N/A', '461,965', '2,144', '122,332,384', '1,458,359', '83,883,596', 'Europe', '2', '466', '1', '', '', '3,944']
['5', 'Brazil', '38,160,672', '', '708,373', '', '36,249,161', '', '1,203,138', 'N/A', '177,200', '3,289', '63,776,166', '296,146', '215,353,593', 'South America', '6', '304', '3', '', '', '5,587']
['6', 'S. Korea', '34,571,873', '', '35,934', '', '34,535,939', '', '0', '', '673,523', '700', '15,804,065', '307,892', '51,329,899', 'Asia', '1', '1,428', '3', '', '', '']
['7', 'Japan', '33,803,572', '', '74,694', '', 'N/A', 'N/A', 'N/A', 'N/A', '269,169', '595', '100,414,883', '799,578', '125,584,838', 'Asia', '4', '1,681', '1', '', '', '95,582']
['8', 'Italy', '26,591,441', '', '194,489', '', '26,162,862', '', '234,090', '240', '441,258', '3,227', '278,771,518', '4,625,933', '60,262,770', 'Europe', '2', '310', '0', '', '', '3,884']
['9', 'UK', '24,812,582', '', '232,112', '', '24,580,470', '', '0', 'N/A', '362,239', '3,389', '522,526,476', '7,628,357', '68,497,907', 'Europe', '3', '295', '0', '', '', '']
['10', 'Russia', '23,713,738', '+79,032', '401,214', '+186', '23,068,286', '+98,252', '244,238', 'N/A', '162,639', '2,752', '273,400,000', '1,875,095', '145,805,947', 'Europe', '6', '363', '1', '542', '1', '1,675']
['11', 'Turkey', '17,232,066', '', '102,174', '', 'N/A', 'N/A', 'N/A', 'N/A', '201,399', '1,194', '162,743,369', '1,902,052', '85,561,976', 'Asia', '5', '837', '1', '', '', '4,024']
['12', 'Spain', '13,914,811', '', '121,760', '', '13,762,417', '', '30,634', '231', '297,840', '2,606', '471,036,328', '10,082,298', '46,719,142', 'Europe', '3', '384', '0', '', '', '656']
['13', 'Australia', '11,738,287', '', '23,752', '', 'N/A', 'N/A', 'N/A', '22', '450,281', '911', '81,916,639', '3,142,326', '26,068,792', 'Australia/Oceania', '2', '1,098', '0', '', '', '1,648']
['14', 'Vietnam', '11,624,114', '', '43,206', '', '10,640,971', '', '939,937', '', '117,470', '437', '85,826,548', '867,342', '98,953,541', 'Asia', '9', '2,290', '1', '', '', '9,499']
['15', 'Taiwan', '10,241,523', '', '19,005', '', '10,222,518', '', '0', '', '428,720', '796', '30,742,304', '1,286,903', '23,888,595', 'Asia', '2', '1,257', '1', '', '', '']
['16', 'Argentina', '10,080,046', '', '130,685', '', '9,949,361', '', '0', '', '219,083', '2,840', '35,716,069', '776,264', '46,010,234', 'South America', '5', '352', '1', '', '', '']
['17', 'Netherlands', '8,623,210', '', '22,992', '', '8,597,059', '', '3,159', 'N/A', '501,016', '1,336', '25,984,435', '1,509,718', '17,211,447', 'Europe', '2', '749', '1', '', '', '184']
['18', 'Mexico', '7,702,582', '', '334,938', '', '6,899,865', '', '467,779', 'N/A', '58,547', '2,546', '20,013,810', '152,124', '131,562,772', 'North America', '17', '393', '7', '', '', '3,556']
['19', 'Iran', '7,625,160', '', '146,741', '', 'N/A', 'N/A', 'N/A', '', '88,641', '1,706', '57,320,267', '666,338', '86,022,837', 'Asia', '11', '586', '2', '', '', '1,176']
['20', 'Indonesia', '6,816,938', '', '161,921', '', '6,647,104', '', '7,913', 'N/A', '24,422', '580', '114,158,919', '408,975', '279,134,505', 'Asia', '41', '1,724', '2', '', '', '28']
['21', 'Poland', '6,624,723', '+100', '120,158', '', 'N/A', 'N/A', 'N/A', 'N/A', '175,537', '3,184', '39,066,091', '1,035,143', '37,739,785', 'Europe', '6', '314', '1', '3', '', '30,965']
['22', 'Colombia', '6,386,157', '', '143,100', '', '6,206,196', '', '36,861', '342', '123,972', '2,778', '36,951,507', '717,327', '51,512,762', 'South America', '8', '360', '1', '', '', '716']
['23', 'Greece', '6,101,379', '', '37,869', '', 'N/A', 'N/A', 'N/A', '', '591,412', '3,671', '102,228,365', '9,909,078', '10,316,637', 'Europe', '2', '272', '0', '', '', '']
['24', 'Austria', '6,081,287', '', '22,542', '', '6,054,934', '', '3,811', '', '670,727', '2,486', '211,273,524', '23,302,116', '9,066,710', 'Europe', '1', '402', '0', '', '', '420']
['25', 'Portugal', '5,633,342', '', '27,790', '', '5,605,552', '+134', '0', '61', '555,525', '2,740', '46,139,518', '4,549,993', '10,140,570', 'Europe', '2', '365', '0', '', '', '']
['26', 'Ukraine', '5,557,995', '', '112,418', '', '5,445,577', '', '0', '', '128,681', '2,603', '32,603,805', '754,855', '43,192,122', 'Europe', '8', '384', '1', '', '', '']
['27', 'Chile', '5,325,080', '', '64,497', '', '5,252,450', '', '8,133', '23', '276,625', '3,350', '50,382,097', '2,617,225', '19,250,195', 'South America', '4', '298', '0', '', '', '422']
['28', 'Malaysia', '5,180,812', '', '37,246', '', '5,115,191', '', '28,375', '4', '156,138', '1,123', '68,580,916', '2,066,869', '33,181,072', 'Asia', '6', '891', '0', '', '', '855']
['29', 'Canada', '4,855,902', '', '56,787', '', '4,763,910', '+4,249', '35,205', '99', '126,494', '1,479', '66,525,130', '1,732,948', '38,388,419', 'North America', '8', '676', '1', '', '', '917']
['30', 'Israel', '4,841,772', '', '12,707', '', '4,798,473', '', '30,592', 'N/A', '519,169', '1,363', '41,373,364', '4,436,346', '9,326,000', 'Asia', '2', '734', '0', '', '', '3,280']
['31', 'Belgium', '4,836,886', '', '34,376', '', '4,796,823', '', '5,687', 'N/A', '414,533', '2,946', '37,018,657', '3,172,590', '11,668,278', 'Europe', '2', '339', '0', '', '', '487']
['32', 'DPRK', '4,772,813', '', '74', '', '4,772,739', '', '0', '', '183,636', '3', '', '', '25,990,679', 'Asia', '5', '351,225', '', '', '', '']
['33', 'Thailand', '4,761,781', '', '34,514', '', '4,692,636', '', '34,631', 'N/A', '67,950', '493', '17,270,775', '246,450', '70,078,203', 'Asia', '15', '2,030', '4', '', '', '494']
['34', 'Czechia', '4,742,356', '+197', '43,279', '', '4,684,184', '+2,243', '14,893', '35', '441,692', '4,031', '57,593,423', '5,364,122', '10,736,784', 'Europe', '2', '248', '0', '18', '', '1,387']
['35', 'Peru', '4,524,326', '', '222,161', '', '4,302,165', '', '0', '4', '134,316', '6,595', '39,010,194', '1,158,115', '33,684,208', 'South America', '7', '152', '1', '', '', '']
['36', 'Switzerland', '4,436,359', '', '14,452', '', '4,414,607', '', '7,300', 'N/A', '505,647', '1,647', '23,833,472', '2,716,487', '8,773,637', 'Europe', '2', '607', '0', '', '', '832']
['37', 'Philippines', '4,132,200', '', '66,795', '', '4,059,836', '', '5,569', 'N/A', '36,728', '594', '36,062,572', '320,531', '112,508,994', 'Asia', '27', '1,684', '3', '', '', '49']
['38', 'South Africa', '4,076,463', '', '102,595', '', '3,912,506', '', '61,362', '192', '67,095', '1,689', '26,795,090', '441,027', '60,756,135', 'Africa', '15', '592', '2', '', '', '1,010']
['39', 'Romania', '3,506,590', '', '68,673', '', '3,437,917', '+1,510', '0', '36', '184,253', '3,608', '28,377,007', '1,491,068', '19,031,335', 'Europe', '5', '277', '1', '', '', '']
['40', 'Denmark', '3,183,756', '', '8,814', '', '3,174,942', '', '0', '', '545,636', '1,511', '129,333,107', '22,165,247', '5,834,950', 'Europe', '2', '662', '0', '', '', '']
['41', 'Hong Kong', '2,924,675', '', '14,364', '', '2,909,723', '', '588', 'N/A', '384,608', '1,889', '76,127,725', '10,011,143', '7,604,299', 'Asia', '3', '529', '0', '', '', '77']
['42', 'Singapore', '2,827,115', '', '1,933', '', '2,801,164', '+8,006', '24,018', '9', '475,661', '325', '24,756,666', '4,165,302', '5,943,546', 'Asia', '2', '3,075', '0', '', '', '4,041']
['43', 'Sweden', '2,745,098', '', '26,433', '', '2,709,602', '+279', '9,063', 'N/A', '268,628', '2,587', '19,500,873', '1,908,301', '10,218,971', 'Europe', '4', '387', '1', '', '', '887']
['44', 'Serbia', '2,604,837', '', '18,057', '', '2,578,372', '+4,788', '8,408', '', '301,032', '2,087', '13,333,401', '1,540,896', '8,653,016', 'Europe', '3', '479', '1', '', '', '972']
['45', 'New Zealand', '2,533,522', '', '5,206', '', '2,522,496', '', '5,820', '', '517,235', '1,063', '7,768,604', '1,586,011', '4,898,203', 'Australia/Oceania', '2', '941', '1', '', '', '1,188']
['46', 'Iraq', '2,465,545', '', '25,375', '', '2,439,497', '', '673', '', '58,474', '602', '19,544,451', '463,523', '42,164,965', 'Asia', '17', '1,662', '2', '', '', '16']
['47', 'Hungary', '2,220,168', '', '48,881', '', '2,152,155', '', '19,132', '', '231,117', '5,088', '11,394,556', '1,186,160', '9,606,259', 'Europe', '4', '197', '1', '', '', '1,992']
['48', 'Bangladesh', '2,046,165', '', '29,477', '', 'N/A', 'N/A', 'N/A', 'N/A', '12,188', '176', '15,254,399', '90,862', '167,885,689', 'Asia', '82', '5,695', '11', '', '', '109']
['49', 'Slovakia', '1,870,010', '', '21,167', '', '1,848,129', '', '714', '23', '342,481', '3,877', '7,448,789', '1,364,199', '5,460,193', 'Europe', '3', '258', '1', '', '', '131']
['50', 'Georgia', '1,855,289', '', '17,132', '', 'N/A', 'N/A', 'N/A', '', '467,476', '4,317', '16,920,079', '4,263,340', '3,968,738', 'Asia', '2', '232', '0', '', '', '15,524']
['51', 'Jordan', '1,746,997', '', '14,122', '', '1,731,007', '', '1,868', '59', '169,597', '1,371', '17,201,885', '1,669,945', '10,300,869', 'Asia', '6', '729', '1', '', '', '181']
['52', 'Ireland', '1,726,402', '', '9,376', '', '1,715,650', '', '1,376', '19', '343,891', '1,868', '13,083,449', '2,606,161', '5,020,199', 'Europe', '3', '535', '0', '', '', '274']
['53', 'Pakistan', '1,581,936', '', '30,664', '', '1,538,689', '', '12,583', '', '6,893', '134', '30,589,153', '133,292', '229,488,994', 'Asia', '145', '7,484', '8', '', '', '55']
['54', 'Finland', '1,510,606', '', '11,140', '', '1,495,516', '+299', '3,950', 'N/A', '271,938', '2,005', '12,108,977', '2,179,850', '5,554,960', 'Europe', '4', '499', '0', '', '', '711']
['55', 'Norway', '1,506,024', '+116', '5,732', '', '1,496,441', '+110', '3,851', 'N/A', '273,258', '1,040', '11,002,430', '1,996,315', '5,511,370', 'Europe', '4', '962', '1', '21', '', '699']
['56', 'Kazakhstan', '1,411,831', '', '13,848', '', '1,383,020', '', '14,963', '24', '73,514', '721', '11,575,012', '602,707', '19,205,043', 'Asia', '14', '1,387', '2', '', '', '779']
['57', 'Lithuania', '1,382,183', '', '9,839', '', '1,351,494', '', '20,850', 'N/A', '519,284', '3,696', '10,540,357', '3,959,997', '2,661,708', 'Europe', '2', '271', '0', '', '', '7,833']
['58', 'Slovenia', '1,354,394', '+64', '7,100', '', '1,345,575', '+218', '1,719', 'N/A', '651,767', '3,417', '2,847,701', '1,370,382', '2,078,034', 'Europe', '2', '293', '1', '31', '', '827']
['59', 'Bulgaria', '1,333,154', '', '38,665', '', '1,289,796', '', '4,693', '30', '194,775', '5,649', '11,522,885', '1,683,501', '6,844,597', 'Europe', '5', '177', '1', '', '', '686']
['60', 'Guatemala', '1,280,858', '', '20,272', '', '1,259,965', '', '621', '5', '68,922', '1,091', '7,593,848', '408,622', '18,584,039', 'North America', '15', '917', '2', '', '', '33']
['61', 'Croatia', '1,279,927', '', '18,518', '', '1,258,432', '', '2,977', '', '315,308', '4,562', '5,660,084', '1,394,355', '4,059,286', 'Europe', '3', '219', '1', '', '', '733']
['62', 'Morocco', '1,278,055', '', '16,298', '', 'N/A', 'N/A', 'N/A', 'N/A', '33,835', '431', '13,001,033', '344,191', '37,772,756', 'Africa', '30', '2,318', '3', '', '', '148']
['63', 'Lebanon', '1,243,838', '', '10,952', '', '1,087,587', '', '145,299', '74', '186,068', '1,638', '4,795,578', '717,380', '6,684,849', 'Asia', '5', '610', '1', '', '', '21,736']
['64', 'Costa Rica', '1,238,883', '', '9,428', '', 'N/A', 'N/A', 'N/A', 'N/A', '239,058', '1,819', '4,659,757', '899,158', '5,182,354', 'North America', '4', '550', '1', '', '', '71,154']
['65', 'Bolivia', '1,210,433', '', '22,407', '', '1,177,145', '', '10,881', '220', '100,931', '1,868', '2,710,261', '225,993', '11,992,656', 'South America', '10', '535', '4', '', '', '907']
['66', 'Tunisia', '1,153,361', '', '29,423', '', 'N/A', 'N/A', 'N/A', 'N/A', '95,741', '2,442', '5,013,383', '416,164', '12,046,656', 'Africa', '10', '409', '2', '', '', '1,157']
['67', 'Cuba', '1,115,169', '', '8,530', '', '1,106,575', '', '64', '', '98,638', '754', '14,394,534', '1,273,216', '11,305,652', 'North America', '10', '1,325', '1', '', '', '6']
['68', 'Ecuador', '1,070,121', '', '36,043', '', '1,034,078', '', '0', '', '59,079', '1,990', '3,082,403', '170,173', '18,113,361', 'South America', '17', '503', '6', '', '', '']
['69', 'UAE', '1,067,030', '', '2,349', '', 'N/A', 'N/A', 'N/A', '', '105,837', '233', '200,732,262', '19,910,389', '10,081,785', 'Asia', '9', '4,292', '0', '', '', '1,007']
['70', 'Panama', '1,049,089', '', '8,666', '', '1,040,268', '', '155', '16', '235,911', '1,949', '7,811,039', '1,756,488', '4,446,964', 'North America', '4', '513', '1', '', '', '35']
['71', 'Uruguay', '1,041,111', '', '7,664', '', '1,030,944', '', '2,503', '18', '297,799', '2,192', '6,114,822', '1,749,083', '3,496,016', 'South America', '3', '456', '1', '', '', '716']
['72', 'Mongolia', '1,011,388', '', '2,284', '', '1,009,069', '', '35', 'N/A', '299,397', '676', '4,030,048', '1,193,000', '3,378,078', 'Asia', '3', '1,479', '1', '', '', '10']
['73', 'Nepal', '1,003,450', '', '12,031', '', '991,322', '', '97', '', '33,199', '398', '6,047,766', '200,088', '30,225,582', 'Asia', '30', '2,512', '5', '', '', '3']
['74', 'Belarus', '994,037', '', '7,118', '', '985,592', '', '1,327', '', '105,381', '755', '13,646,641', '1,446,722', '9,432,800', 'Europe', '9', '1,325', '1', '', '', '141']
['75', 'Latvia', '981,106', '', '6,523', '', '971,406', '', '3,177', '', '530,661', '3,528', '7,885,792', '4,265,272', '1,848,837', 'Europe', '2', '283', '0', '', '', '1,718']
['76', 'Saudi Arabia', '841,469', '', '9,646', '', 'N/A', 'N/A', 'N/A', '', '23,475', '269', '45,481,735', '1,268,848', '35,844,909', 'Asia', '43', '3,716', '1', '', '', '109']
['77', 'Azerbaijan', '834,189', '', '10,377', '', '823,770', '', '42', '', '80,988', '1,007', '7,721,568', '749,652', '10,300,205', 'Asia', '12', '993', '1', '', '', '4']
['78', 'Paraguay', '819,221', '', '20,040', '', 'N/A', 'N/A', 'N/A', 'N/A', '112,132', '2,743', '2,657,506', '363,751', '7,305,843', 'South America', '9', '365', '3', '', '', '13,806']
['79', 'Bahrain', '729,549', '', '1,574', '', '727,915', '', '60', 'N/A', '408,944', '882', '10,948,549', '6,137,138', '1,783,983', 'Asia', '2', '1,133', '0', '', '', '34']
['80', 'Sri Lanka', '672,661', '', '16,888', '', '655,741', '', '32', '', '31,177', '783', '6,486,117', '300,619', '21,575,842', 'Asia', '32', '1,278', '3', '', '', '1']
['81', 'Dominican Republic', '670,627', '', '4,384', '', '666,104', '', '139', '4', '60,655', '397', '3,740,928', '338,350', '11,056,370', 'North America', '16', '2,522', '3', '', '', '13']
['82', 'Kuwait', '666,551', '', '2,570', '', 'N/A', 'N/A', 'N/A', '', '152,169', '587', '8,455,743', '1,930,391', '4,380,326', 'Asia', '7', '1,704', '1', '', '', '855']
['83', 'Cyprus', '660,854', '', '1,364', '', '659,490', '', '0', '', '540,184', '1,115', '9,640,118', '7,879,860', '1,223,387', 'Asia', '2', '897', '0', '', '', '']
['84', 'Myanmar', '641,422', '', '19,495', '', '620,159', '', '1,768', '', '11,614', '353', '11,540,638', '208,967', '55,227,143', 'Asia', '86', '2,833', '5', '', '', '32']
['85', 'Moldova', '628,673', '', '12,159', '', 'N/A', 'N/A', 'N/A', 'N/A', '156,652', '3,030', '3,216,305', '801,437', '4,013,171', 'Europe', '6', '330', '1', '', '', '28,001']
['86', 'Estonia', '625,771', '+778', '3,001', '', 'N/A', 'N/A', 'N/A', 'N/A', '473,384', '2,270', '3,772,787', '2,854,042', '1,321,910', 'Europe', '2', '440', '0', '589', '', '73,969']
['87', 'Palestine', '621,008', '', '5,404', '', '615,445', '', '159', '', '116,173', '1,011', '3,078,533', '575,907', '5,345,541', 'Asia', '9', '989', '2', '', '', '30']
['88', 'Venezuela', '552,695', '', '5,856', '', '546,537', '', '302', '31', '18,885', '200', '3,359,014', '114,771', '29,266,991', 'South America', '53', '4,998', '9', '', '', '10']
['89', 'Egypt', '516,023', '', '24,613', '', '442,182', '', '49,228', '122', '4,861', '232', '3,693,367', '34,792', '106,156,692', 'Africa', '206', '4,313', '29', '', '', '464']
['90', 'Qatar', '514,524', '', '690', '', '513,687', '', '147', '16', '172,664', '232', '4,065,369', '1,364,257', '2,979,915', 'Asia', '6', '4,319', '1', '', '', '49']
['91', 'Libya', '507,274', '', '6,437', '', '500,835', '', '2', '', '72,048', '914', '2,483,848', '352,782', '7,040,745', 'Africa', '14', '1,094', '3', '', '', '0.3']
['92', 'Ethiopia', '501,117', '', '7,574', '', '488,171', '', '5,372', '', '4,148', '63', '5,565,340', '46,066', '120,812,698', 'Africa', '241', '15,951', '22', '', '', '44']
['93', 'RÃ©union', '494,595', '', '921', '', 'N/A', 'N/A', 'N/A', 'N/A', '544,672', '1,014', '1,603,660', '1,766,027', '908,061', 'Africa', '2', '986', '1', '', '', '82,706']
['94', 'Honduras', '474,590', '', '11,165', '', 'N/A', 'N/A', 'N/A', 'N/A', '46,432', '1,092', '1,660,662', '162,472', '10,221,247', 'North America', '22', '915', '6', '', '', '32,372']
['95', 'Armenia', '451,272', '', '8,775', '', '435,162', '', '7,335', '', '151,843', '2,953', '3,242,901', '1,091,164', '2,971,966', 'Asia', '7', '339', '1', '', '', '2,468']
['96', 'Bosnia and Herzegovina', '403,443', '', '16,374', '', '379,084', '', '7,985', '', '124,162', '5,039', '1,884,721', '580,036', '3,249,317', 'Europe', '8', '198', '2', '', '', '2,457']
['97', 'Oman', '399,449', '', '4,628', '', 'N/A', 'N/A', 'N/A', '', '75,028', '869', '25,000,000', '4,695,724', '5,323,993', 'Asia', '13', '1,150', '0', '', '', '1,907']
['98', 'Luxembourg', '386,030', '', '1,232', '', 'N/A', 'N/A', 'N/A', '', '600,946', '1,918', '4,587,145', '7,140,959', '642,371', 'Europe', '2', '521', '0', '', '', '106,026']
['99', 'North Macedonia', '349,868', '', '9,958', '', '337,068', '', '2,842', '', '168,100', '4,785', '2,226,216', '1,069,626', '2,081,304', 'Europe', '6', '209', '1', '', '', '1,365']
['100', 'Zambia', '349,304', '', '4,069', '', '341,316', '', '3,919', '', '17,940', '209', '4,112,961', '211,244', '19,470,234', 'Africa', '56', '4,785', '5', '', '', '201']
['101', 'Kenya', '344,130', '', '5,689', '', '337,309', '', '1,132', 'N/A', '6,122', '101', '3,967,062', '70,569', '56,215,221', 'Africa', '163', '9,881', '14', '', '', '20']
['102', 'Albania', '334,726', '', '3,602', '', '329,428', '', '1,696', '', '116,777', '1,257', '1,941,032', '677,173', '2,866,374', 'Europe', '9', '796', '1', '', '', '592']
['103', 'Botswana', '330,409', '', '2,801', '', '327,049', '', '559', '1', '135,349', '1,147', '2,026,898', '830,300', '2,441,162', 'Africa', '7', '872', '1', '', '', '229']
['104', 'Brunei', '321,235', '', '225', '', '243,601', '', '77,409', '3', '721,178', '505', '717,784', '1,611,437', '445,431', 'Asia', '1', '1,980', '1', '', '', '173,784']
['105', 'Montenegro', '294,899', '', '2,834', '', '291,794', '', '271', 'N/A', '469,622', '4,513', '2,764,972', '4,403,172', '627,950', 'Europe', '2', '222', '0', '', '', '432']
['106', 'Algeria', '272,010', '', '6,881', '', '183,061', '', '82,068', '', '5,998', '152', '230,960', '5,093', '45,350,148', 'Africa', '167', '6,591', '196', '', '', '1,810']
['107', 'Nigeria', '267,173', '', '3,155', '', '259,953', '', '4,065', '11', '1,233', '15', '5,708,974', '26,339', '216,746,934', 'Africa', '811', '68,700', '38', '', '', '19']
['108', 'Zimbabwe', '265,975', '', '5,730', '', '258,888', '', '1,357', '12', '17,348', '374', '2,525,756', '164,744', '15,331,428', 'Africa', '58', '2,676', '6', '', '', '89']
['109', 'Uzbekistan', '253,662', '', '1,637', '', '241,486', '', '10,539', '23', '7,378', '48', '1,377,915', '40,077', '34,382,084', 'Asia', '136', '21,003', '25', '', '', '307']
['110', 'Mozambique', '233,731', '', '2,250', '', '228,805', '', '2,676', '11', '7,064', '68', '1,371,127', '41,437', '33,089,461', 'Africa', '142', '14,706', '24', '', '', '81']

In [114]:
df[:230]

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,1,USA,"110,047,807","+6,444","1,190,000",+13,"107,820,312","+15,017","1,037,495","1,754",...,"1,186,546,440","3,543,990","334,805,269",North America,3,281,0,19,0.04,"3,099"
1,2,India,"45,009,660","+1,040","533,337",+4,N/A,N/A,N/A,N/A,...,"930,797,975","661,721","1,406,631,776",Asia,31,"2,637",2,0.7,,3
2,3,France,"40,138,560",,"167,642",,"39,970,918",,0,,...,"271,490,188","4,139,547","65,584,518",Europe,2,391,0,,,
3,4,Germany,"38,751,299",,"179,854",,"38,240,600",,"330,845",N/A,...,"122,332,384","1,458,359","83,883,596",Europe,2,466,1,,,"3,944"
4,5,Brazil,"38,160,672",,"708,373",,"36,249,161",,"1,203,138",N/A,...,"63,776,166","296,146","215,353,593",South America,6,304,3,,,"5,587"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,226,Diamond Princess,712,,13,,699,,0,,...,,,,,,,,,,
226,227,Tokelau,80,,,,,,80,,...,,,"1,378",Australia/Oceania,17,,,,,"58,055"
227,228,Vatican City,29,,,,29,,0,,...,,,799,Europe,28,,,,,
228,229,Western Sahara,10,,1,,9,,0,,...,,,"626,161",Africa,"62,616","626,161",,,,
229,230,MS Zaandam,9,,2,,7,,0,,...,,,,,,,,,,